# Configure ONTAP SVM for NFS & iSCSI protocol

- name: Configure an ONTAP SVM for iSCSI protocol
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    netapp_hostname: 192.168.0.101
    netapp_username: admin
    netapp_password: Netapp1!
  tasks:
    - name: Enable iSCSI protocol
      na_ontap_svm:
        state: present
        name: svm1
        allowed_protocols: nfs,iscsi
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
    - name: Create interface
      na_ontap_interface:
        state: present
        interface_name: svm1_iscsi
        home_port: e0d
        home_node: cluster1-01
        role: data
        protocols: iscsi
        admin_status: up
        address: 192.168.0.45
        netmask: 255.255.255.0
        vserver: svm1
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false
    - name: Enable iscsi service
      na_ontap_iscsi:
        state: present
        service_state: started
        vserver: svm1
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: false        

